### ISSUE TITLE
How to open pre-populated sqlite database?

### ISSUE THREAD

**Issue by ghost** [jvail/spatiasql.js#16]
Great work. How to open pre-populated database with .sqlite extension? I don't find such example in readme file. Can someone, please, give me some example of opening sqlite DB?

**Comment by jvail** [comment]
There are plenty of examples: Please take look at test_sql_stmts.js in the tests folder (node.js), or sql.js (plain js) readme or the TS source here: https://github.com/jvail/spatialitebrowser
