### ISSUE TITLE
Working example with sample data from geopackage.org

### ISSUE THREAD

**Issue by sweco-seajaa** [jvail/spatiasql.js#2]
Cool project!

I tried to open some of the sample files from http://www.geopackage.org/#sampledata but failed to export any data from "the_geom" columns. Only getting null values as a result and no error message.

Would be nice if you could submit a working example or point us in the right direction.

**Comment by jvail** [comment]
I quickly tried it in the browser example with this file: [simple_sewer_features](http://www.geopackage.org/data/simple_sewer_features.gpkg). Seems to be ok.

There are also geopackage testcases in the repos' test folder that did not fail (as far as I remember).

**Comment by sweco-seajaa** [comment]
The testcases pointed me in the right direction. Now it works just fine!

Thanks!
