### ISSUE TITLE
Can this work with IDFS?

### ISSUE THREAD

**Issue by ndarilek** [jvail/spatiasql.js#6]
Took me a while of digging to realize that this only likely worked with in-memory data due to sql.js. Is this accurate?

If so, is there any possibility of using IDFS, or some other backend for using large files in the browser? I've been investigating for a while and suspect the answer is no, but thought I'd ask to be sure.

It might be worth adding a "this only works with in-memory data" blurb in the README.md. I'm not super familiar with the Emscripten ecosystem yet, and was very excited about this until I realized that using my 2 GB databases was likely a no-go. :)

Thanks.

**Comment by jvail** [comment]
Hi @ndarilek, 
yes, currently you have to load the complete db into memory... There are a few discussions regarding persistence here: https://github.com/kripken/sql.js/issues?utf8=%E2%9C%93&q=IDBFS. You might have read them already.

I am curious: Did try to load the 2gig file into the web (wasm) example? What happens? :)

**Comment by ndarilek** [comment]
Heh, no, I didn't even bother trying. My eventual target for this is a 
web browser running on a low-end device which I wouldn't mind losing if 
it got wet, so with that perspective in mind, I probably wouldn't have 2 
GB of RAM to burn. :) Plus I think the database is even larger once the 
routing data is added.

Thanks for the pointer, I'll check that discussion out.
